version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    depends_on:
      - pgdb
      - redis
  redis:
    image: redis
  celery:
    build: .
    command: celery -A fampay worker -B -l DEBUG -P threads
    volumes:
      - .:/app
    env_file:
      - docker.env
    depends_on:
      - django
      - redis
  pgdb:
    image: postgres
    ports:
      - "5432"
    container_name: pgdb
    env_file:
      - docker.env
    volumes:
      - ./data/db:/var/lib/postgresql/data/
