# Generated by Django 4.1 on 2022-08-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('video_id', models.CharField(max_length=256)),
                ('publish_time', models.DateTimeField()),
            ],
        ),
    ]
